version: 2.1

orbs:
  python: circleci/python@0.3.2
  aws-cli: circleci/aws-cli@1.2.1

jobs:
  build-and-test:
    executor:
      name: python/default
      tag: "3.7"
    steps:
      - checkout
      - run:
          name: Setup Virtual env
          command: |
            virtualenv -p python3.7 env
            echo "source ./env/bin/activate" >> $BASH_ENV
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
      - run:
          name: Create ENV file
          command: env > .env
      - run:
          name: Test
          command: pytest
      - run:
          name: Create Zipfile archive of Dependencies
          command: |
            cd env/lib/python3.7/site-packages
            zip -r9 ../../../../function.zip .
      - run:
          name: Add App to Zipfile
          command: zip -g ./function.zip .env -r app
      - persist_to_workspace:
          root: .
          paths:
            - function.zip
